# Generated by Django 5.2.4 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_eventmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_fee',
            field=models.DecimalField(default=0.0, max_digits=8, decimal_places=2),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_option',
            field=models.CharField(choices=[('online', 'Online Payment'), ('onsite', 'Pay at Event')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='amount_paid',
            field=models.DecimalField(default=0.0, max_digits=8, decimal_places=2),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registration',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
