# Generated by Django 5.2.4 on 2026-03-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('coordinator', 'Coordinator'), ('leader', 'Leader'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
