# Generated by Django 5.2.4 on 2025-09-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_list', 'Waiting List')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('why_join', models.TextField(verbose_name='Why do you want to join this club?')),
                ('skills', models.TextField(verbose_name='What skills can you contribute?')),
                ('experience', models.TextField(blank=True, verbose_name='Previous experience')),
                ('expectations', models.TextField(verbose_name='What do you expect from the club?')),
                ('notes', models.TextField(blank=True, verbose_name='Review Notes')),
            ],
        ),
    ]
