# Generated by Django 5.2.4 on 2025-10-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='college_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='College Email ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('bca', 'BCA'), ('mca', 'MCA'), ('bba', 'BBA'), ('mba', 'MBA'), ('bsc', 'B.Sc'), ('msc', 'M.Sc'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('alumni', 'Alumni')], max_length=10),
        ),
    ]
