# Generated by Django 5.2.4 on 2025-10-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='member', max_length=20),
        ),
    ]
