# Generated by Django 5.2.4 on 2026-03-31 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_membership_role'),
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_club',
            field=models.ForeignKey(blank=True, help_text='Assign one club to this admin user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_users', to='clubs.club'),
        ),
    ]
